sudo: required
dist: trusty

services:
  - docker

before_install:
  - docker pull loonygnoll/lemongrab-build-gentoo
  - gem install coveralls-lcov

script:
  - docker run -v $TRAVIS_BUILD_DIR:$TRAVIS_BUILD_DIR
    -e TRAVIS_BUILD_DIR
    -e TRAVIS
    -e TRAVIS_REPO_SLUG
    -e TRAVIS_JOB_ID
    -e TRAVIS_PULL_REQUEST
    -e TRAVIS_BRANCH
    -e COVERALLS_REPO_TOKEN
    --entrypoint=$TRAVIS_BUILD_DIR/build-in-docker.sh
    loonygnoll/lemongrab-build-gentoo

os:
  - linux
